import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { ClerkProvider } from "@clerk/nextjs";
import Sidenav from "./_components/Sidenav";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={cn(
            "min-h-screen bg-background font-sans max-w-7xl mx-auto antialiased",
            fontSans.variable
          )}
        >
          <div className="grid grid-cols-4  justify-center">
            <div className="col-span-1">
              <Sidenav />
            </div>
            <div className="col-span-2 border-l-[0.5px] h-screen p-2 border-l-gray-500">
              {children}
            </div>
            <div className="">
              <p>Follows</p>
            </div>
          </div>
        </body>
      </html>
    </ClerkProvider>
  );
}
